version: "3.9"  # optional since v1.27.0
services:
  sadhelx-be-usermgmt_svc:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SERVER=DEVELOPMENT
    ports:
      - 8088:8088
    restart: unless-stopped
    networks:
      - sadhelx_network
    mem_limit: 256m

  sadhelx-be-usermgmt_db:
    image: postgres

networks:
  sadhwlx_network:
    external: true


